services:
  composer:
    image: composer
    environment:
      - COMPOSER_CACHE_DIR=/app/var/composer/cache
    volumes:
      - .:/app
    profiles: ['tools']

  console:
    extends:
      service: fpm
    working_dir: /app
    entrypoint: bin/console
    profiles: ['tools']

  fpm:
    build:
      context: ./docker/php
    restart: always
    volumes:
      - .:/app

  nginx:
    image: nginx
    restart: always
    ports:
      - 9080:80
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
